### ISSUE TITLE
New Relic Stress Test Screenshot (Service - Dev)

### ISSUE THREAD

**Issue by IsaacLeeWebDev** [systemdesignzallow/gosackService#12]
Show the New Relic dashboard displaying your service's metrics during a stress test (in development) with a screenshot (link to imgr)

**Comment by zibmcnib** [comment]
Add screenshots for post route

**Comment by zibmcnib** [comment]
<https://github.com/systemdesignzallow/gosackDocumentation/blob/master/benchmarking.md>
