### ISSUE TITLE
MariaDB Exploration

### ISSUE THREAD

**Issue by zibmcnib** [systemdesignzallow/gosackService#2]
- [x] Get CLI Running  
- [x] Create Tables
- [x] Import Data
- [x] Learn how to profile query performance.
- [x] Create Documentation

**Comment by IsaacLeeWebDev** [comment]
@zibmcnib `enhancement`s are typically for creating a new feature (i.e. submitting new code). Perhaps a better label might be `investigation task`, or `research`.

**Comment by zibmcnib** [comment]
Awesome, fixed!
