### ISSUE TITLE
Database Exploration Prerequisites

### ISSUE THREAD

**Issue by zibmcnib** [systemdesignzallow/gosackService#5]
- [x] Create 1e7 records

**Comment by IsaacLeeWebDev** [comment]
Review the requirements for new features!

> All Pull Requests for features must:
> - [ ] Contain unit or performance tests
> - [ ] Have a review performed by one person on the team
>   - [ ] Receive at least one improvement as a result of the code review

**Comment by zibmcnib** [comment]
Completed record generation script.
