### ISSUE TITLE
Perform one or more core DB queries + Sample Results

### ISSUE THREAD

**Issue by IsaacLeeWebDev** [systemdesignzallow/gosackService#9]
## To close this issue...

Place a link to a GitHub Gist with this information in your engineering journal, and/or in a comment on this Issue.

## Instructions:

- [x] Verify that all queries used by your API will run in under 50ms. To achieve this goal, you may need to do some performance tuning work on your DBMS.
  - Confirm performance by running the queries used by your API either by:
    - Writing tests (using/modifying existing tests is ok)
    - Using the DB console to execute and time queries
  - Notes:
    - Craft your queries to use records that are within the last 10% of your dataset.
    - Your queries should be the same queries you would use to support your API. Benchmarking a query that your service wouldn't use isn't helpful to determining performance.
    - Queries will be different depending on the technology in use.
    - 50ms is the upper limit. Most queries for this project should be optimizable to around 10ms or less. While most queries for this project can be optimized to execute in significantly less than 50ms, there may be very legitimate reasons why this goal might not be reachable in your circumstance.
- [x] Compare the performance of these two systems against each other and pick the one that performs best for *your* use-case.
- [x] Select one of your DBMS options for your final implementation
  - Once you have made a final decision on DBMS:
    - Update your API server to use that Database
    - Verify your UI still works as expected

**Comment by zibmcnib** [comment]
I have some benchmarks across both databases for queries, however, I have two issues.
1. The databases were not hosted in identical conditions, Maria was running on a dedicated linux install and Cassandra was run in a WSL instance on Windows. I realized how silly this was after the significant performance delta caused me to want to re-test Cassandra under the same conditions.

2. According to the documentation, the way that I profiled the query performance is quite expensive for cassandra. I have not read anything saying that query bench-marking for maria has a similar penalty.

**Comment by IsaacLeeWebDev** [comment]
I believe Cassandra only works in a Linux environment. You will likely deploy to a Linux environment as well, so I'd suggest benchmarking MariaDB in a Linux environment as well, if you really want to level the playing-field before making your choice. That's your call.
